//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenArt.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCategory
    {
        public tCategory()
        {
            this.tCategoryPicture = new HashSet<tCategoryPicture>();
            this.tProduct = new HashSet<tProduct>();
        }
    
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryTypeID { get; set; }
    
        public virtual ICollection<tCategoryPicture> tCategoryPicture { get; set; }
        public virtual tCategoryType tCategoryType { get; set; }
        public virtual ICollection<tProduct> tProduct { get; set; }
    }
}
