//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenArt.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNewsItem
    {
        public tNewsItem()
        {
            this.tNewsItemPicture = new HashSet<tNewsItemPicture>();
        }
    
        public int NewsItemID { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public bool Published { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual ICollection<tNewsItemPicture> tNewsItemPicture { get; set; }
    }
}
