//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenArt.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProduct
    {
        public tProduct()
        {
            this.tOrderDetail = new HashSet<tOrderDetail>();
            this.tProductAttributeValue = new HashSet<tProductAttributeValue>();
            this.tProductGroupDetail = new HashSet<tProductGroupDetail>();
            this.tProductMaterial = new HashSet<tProductMaterial>();
            this.tProductPicture = new HashSet<tProductPicture>();
            this.tSetDetail = new HashSet<tSetDetail>();
            this.tWarehouse = new HashSet<tWarehouse>();
        }
    
        public int ProductID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string SupplierArticleNumber { get; set; }
        public string GardenArtArticleNumber { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public string Description { get; set; }
        public int ProductSizeWidth { get; set; }
        public int ProductSizeHeight { get; set; }
        public int ProductSizeDepth { get; set; }
        public string PackageInfo { get; set; }
        public string Package { get; set; }
        public string PackageSize { get; set; }
        public decimal GrossWeight { get; set; }
        public decimal NetWeight { get; set; }
        public int ItemsPerContainer { get; set; }
        public decimal VolumePerItem { get; set; }
        public string Factory { get; set; }
        public string Supplier { get; set; }
        public decimal CostUSD { get; set; }
        public decimal PurchasePriceUSD { get; set; }
        public decimal SellingPriceDirectUSD20 { get; set; }
        public decimal SellingPriceDirectUSD10 { get; set; }
        public decimal SellingPriceWarehouseSEK { get; set; }
        public Nullable<int> FrameID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public decimal SellingPriceConsumerSEK { get; set; }
        public Nullable<int> FrameColorID { get; set; }
        public Nullable<int> MaterialColorID { get; set; }
        public string ProductSizeInfo { get; set; }
    
        public virtual tCategory tCategory { get; set; }
        public virtual tFrame tFrame { get; set; }
        public virtual tFrameColor tFrameColor { get; set; }
        public virtual tMaterialColor tMaterialColor { get; set; }
        public virtual ICollection<tOrderDetail> tOrderDetail { get; set; }
        public virtual tSupplier tSupplier { get; set; }
        public virtual ICollection<tProductAttributeValue> tProductAttributeValue { get; set; }
        public virtual ICollection<tProductGroupDetail> tProductGroupDetail { get; set; }
        public virtual ICollection<tProductMaterial> tProductMaterial { get; set; }
        public virtual ICollection<tProductPicture> tProductPicture { get; set; }
        public virtual ICollection<tSetDetail> tSetDetail { get; set; }
        public virtual ICollection<tWarehouse> tWarehouse { get; set; }
    }
}
