//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenArt.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProductAttribute
    {
        public tProductAttribute()
        {
            this.tProductAttributeValue = new HashSet<tProductAttributeValue>();
        }
    
        public int ProductAttributeID { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tProductAttributeValue> tProductAttributeValue { get; set; }
    }
}
