//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenArt.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProductGroup
    {
        public tProductGroup()
        {
            this.tProductGroupDetail = new HashSet<tProductGroupDetail>();
            this.tProductGroupPicture = new HashSet<tProductGroupPicture>();
        }
    
        public int ProductGroupID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<tProductGroupDetail> tProductGroupDetail { get; set; }
        public virtual ICollection<tProductGroupPicture> tProductGroupPicture { get; set; }
    }
}
