//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenArt.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSet
    {
        public tSet()
        {
            this.tSetDetail = new HashSet<tSetDetail>();
            this.tSetPicture = new HashSet<tSetPicture>();
        }
    
        public int SetID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tSetDetail> tSetDetail { get; set; }
        public virtual ICollection<tSetPicture> tSetPicture { get; set; }
    }
}
