//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenArt.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tWarehouse
    {
        public int WarehouseID { get; set; }
        public int WarehouseLocationID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public int Ordered { get; set; }
        public int Available { get; set; }
    
        public virtual tWarehouseLocation tWarehouseLocation { get; set; }
        public virtual tProduct tProduct { get; set; }
    }
}
