//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenArt.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tWarehouseLocation
    {
        public tWarehouseLocation()
        {
            this.tWarehouse = new HashSet<tWarehouse>();
        }
    
        public int WarehouseLocationID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<tWarehouse> tWarehouse { get; set; }
    }
}
